server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

logging:
  level:
    root: INFO
    org.mdmi: TRACE
    org.springframework.web: INFO
    org.springframework.security: INFO

fhirterminology:
    userName: user
    password: user
    url: http://ec2-18-188-214-103.us-east-2.compute.amazonaws.com:8080/fhir

origins:
  url: ""
